### PR TITLE
Convert proto3 maps into MutableMapping Python constructs

### PR DESCRIPTION
**Pull request by drather19**
Here's an example of converting proto3 maps into MutableMapping types rather than defaulting to RepeatedScalarFieldContainer constructs...

Referencing #12 for more context.

### CODE REVIEW

**Comment by drather19** [comment]
Bueller?

**Comment by lfaraone** [comment]
@drather19: could you sign https://opensource.dropbox.com/cla/ ?

**Comment by drather19** [comment]
Certainly!

Here's a sample protobuf file:
```protobuf
syntax = "proto3";

package test;

message TestMessage {
    string something = 1;
}

message TestRequest {
    map<int64, string> test_map = 1;
    repeated TestMessage test_complex_list = 2;
}
```

Here's the generated `test_pb2.pyi` with the original code:
```python
# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.message import (
    Message,
)

from typing import (
    Iterable,
    Text,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer,
)

class TestMessage(Message):
    something = ... # type: Text
    
    def __init__(self,
        something : Text = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TestMessage: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...

class TestRequest(Message):
    class TestMapEntry(Message):
        key = ... # type: int
        value = ... # type: Text
        
        def __init__(self,
            key : int = None,
            value : Text = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> TestRequest.TestMapEntry: ...
        def MergeFrom(self, other_msg: Message) -> None: ...
        def CopyFrom(self, other_msg: Message) -> None: ...
    
    
    @property
    def test_map(self) -> RepeatedScalarFieldContainer[TestRequest.TestMapEntry]: ...
    
    @property
    def test_complex_list(self) -> RepeatedScalarFieldContainer[TestMessage]: ...
    
    def __init__(self,
        test_map : Iterable[TestRequest.TestMapEntry] = None,
        test_complex_list : Iterable[TestMessage] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TestRequest: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...
```

And here's the generated file with the changes:
```python
# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.message import (
    Message,
)

from typing import (
    Text,
    Iterable,
    MutableMapping,
    Mapping,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer,
)

class TestMessage(Message):
    something = ... # type: Text
    
    def __init__(self,
        something : Text = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TestMessage: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...

class TestRequest(Message):
    class TestMapEntry(Message):
        key = ... # type: int
        value = ... # type: Text
        
        def __init__(self,
            key : int = None,
            value : Text = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> TestRequest.TestMapEntry: ...
        def MergeFrom(self, other_msg: Message) -> None: ...
        def CopyFrom(self, other_msg: Message) -> None: ...
    
    
    @property
    def test_map(self) -> MutableMapping[int, Text]: ...
    
    @property
    def test_complex_list(self) -> RepeatedCompositeFieldContainer[TestMessage]: ...
    
    def __init__(self,
        test_map : Mapping[int, Text] = None,
        test_complex_list : Iterable[TestMessage] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TestRequest: ...
    def MergeFrom(self, other_msg: Message) -> None: ...
    def CopyFrom(self, other_msg: Message) -> None: ...
```

**Comment by drather19** [comment]
Signed the CLA... additionally, I believe the merge conflict is due to a similar change made in PR #17 which should already be covered in this PR as well.

**Comment by dzbarsky** [comment]
ok great, should we also stop emitting the `TestMapEntry` now since it is no longer used?

**Comment by drather19** [comment]
We might want to leave them since those entries do get generated in the *.py files by protoc (though I haven't personally had a use for the declarations).

**Comment by dzbarsky** [comment]
OK, I can't think of any use case for anyone using it but it doesn't hurt

**Pull request merged**
