### PR TITLE
import other generated module relatively to package

### PR DESCRIPTION
**Pull request by Evgenus**
When proto files having dependencies, generated stubs imports each other in global fassion, which sometimes leads to broken imports. I've tried to fix that at least for simple cases.

### CODE REVIEW

**Comment by Evgenus** [comment]
related to #32

**Comment by nipunn1313** [comment]
This seems reasonable and would work. Have a couple of questions to make sure we're solving the issue

1 - what case leads to broken imports? It would be good to add some `.proto` files/package to the `proto` directory to illustrate this case to make sure we don't regress this in the future. Some test case `.proto` files that fail without your change and pass with your change will be great.

2 - I notice this diff covers relative imports within the same package. Does the same issue arise when importing something from a parent package, or another package within the same tree? Eg a relative import - eg `import ..parent.other_child_pb2`

**Comment by Evgenus** [comment]
I'm glad you like it.

> 1 - what case leads to broken imports? 

Inside of generated files imports looks like `from folder.proto_file_pb2 import Message as ...` which works only for the case when the `folder is a global package`

> Some test case `.proto` files that fail without your change and pass with your change will be great.

Sure. Can you give me a hint of how to test if the import works inside of `.pyi`?

> 2 - Does the same issue arise when importing something from a parent package, or another package within the same tree?

I think yes. I will improve.

**Comment by nipunn1313** [comment]
I believe if you add `.proto` files to the `proto/` directory, then those will autogenerate `.py` files via protoc and `.pyi` files via mypy-protobuf when you run the testsuite.

This may be tricky to test, since `test.proto` is a global level package in our instantiation. Perhaps to be fully generic, we don't actually want it to be a global level package in our testsuite.

The testsuite uses this line to run protoc - it does a dance to make sure that it generates absolute paths to packages. Perhaps there's something we can change on this line in order to illustrate the bug that your diff is fixing.
https://github.com/dropbox/mypy-protobuf/blob/master/run_test.sh#L20

**Comment by Evgenus** [comment]
After all I realized that I don't actually need this. Accordingly to current implementation of protoc there is only one way of organizing python modules and it is based on imports from globaly available package. Also __init__.py need to be provided manually. So I will close that PR and just go with duplicating whole structure of packages from global module in folder with source .proto files.

**Comment by nipunn1313** [comment]
yes - the __init__.py need to provided manually and it's quite bothersome =\
It's an issue w/ generating python as well

**Pull request closed without merging**
