### PR TITLE
Add typing for Message.DESCRIPTOR

### PR DESCRIPTION
**Pull request by shabbyrobe**
At the moment, there is typing information available for `MyEnum.DESCRIPTOR` but not for `MyMessage.DESCRIPTOR`.

I thought there might have been some non-obvious reason that it wasn't there to begin with -- I had a bit of a spelunk through the issues and history to see if there was a reason -- but came up empty handed and thought I'd just submit something anyway.

I accept the [Dropbox Individual Contributor CLA](https://opensource.dropbox.com/cla/individual/)

_Edit_: Just noticed there's a Go version in here too and the README states that Dropbox use it and would like it to have parity with the Python version. I've updated it, but I don't see any tests for it. What's the actual status of the Go version? The output seems a bit different. If it's unused, I'll leave it alone but if it's used and should be a first-class citizen, I can add a test or two.

### CODE REVIEW

**Comment by nipunn1313** [comment]
This looks great! Would be awesome if you could update `test_generated_mypy.py` with a usage of this Message.DESCRIPTOR as that code is run by python as well as by mypy. A usage there would confirm that this field exists and runs in the protoc generated python + is also typed by mypy.

We have a larger issue #11 for go/python equivalency tests, but we don't have them yet. At Dropbox, we use both versions internally in different parts of the company, so we get a bit of trial-by-fire. I would say - don't worry about writing tests for the go part - we should just wait until #11 is resolved.

Overall LGTM thanks!
If you would like, you can also add yourself to the README as a contributor.

**Comment by shabbyrobe** [comment]
Thanks for the super fast review!

I've added tests to both `test/test_generated_mypy.py` and `test_negative/negative.py`, not 100% sure if I've done it right but it seemed to fail when I did it wrong and work when I did it right!

Given the lack of tests, would you prefer I removed the updates to the Go version or should I leave them in? I did some testing locally to verify the output was valid, but I guess I'm just a bit nervous about breaking someone's workflow!

**Comment by nipunn1313** [comment]
Looks great! Thanks.
We can leave the updates in. We'll fix em  if there's an issue.

**Comment by shabbyrobe** [comment]
Wonderful! Thank you!! When do you expect the next release to go out?

**Comment by nipunn1313** [comment]
I usually just kick one whenever there's a meaningful change. I'll go ahead and kick one out now!

**Pull request merged**
